- hosts: localhost
  roles: 
  - role: jahrik.yay
    install: true
  become: true
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
  tasks:
  - name: Install git
    pacman: name=git
  - include_tasks: tasks/ssh.yml
    tags:
    - ssh
  - include_tasks: tasks/zsh.yml
    tags:
    - zsh
  - include_tasks: tasks/tmux.yml
    tags:
    - tmux
  - include_tasks: tasks/nvim.yml
    tags:
    - nvim
  - include_tasks: tasks/dotfiles.yml
    tags:
    - dotfiles
  - include_tasks: tasks/languages.yml
  - include_tasks: tasks/utils.yml
    tags:
      - utils
