- hosts: localhost
  tasks:
  - name: Add lkarasinski user
    ansible.builtin.user:
      name: "lkarasinski"
      password: "$6$n36uYc1.7ds45gTS$36dYFB1PguMvn1GbghcAuuRnd53K4iMSawqr4H5usZK5Vsm.ioKX8M9Leg7SR2f8DguhdYTFJDMsxMYUxfT4G/"
  - name: Allow the lkarasinski user to run any commands as root
    community.general.sudoers:
      name: run-as-root
      state: present
      user: lkarasinski
      runas: root
      commands: ALL
