- name: Install docker
  become: true
  become_user: lkarasinski
  kewlfft.aur.aur:
    use: yay
    name: docker
- name: Install docker compose
  become: true
  become_user: lkarasinski
  kewlfft.aur.aur:
    use: yay
    name: docker-compose
- name: Start docker service
  ignore_errors: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
- name: Add lkarasinski to docker group
  ansible.builtin.user:
    name: lkarasinski
    groups: docker
    append: true
