- name: Remove dotfiles directory
  ansible.builtin.file: 
    path: "/home/lkarasinski/dotfiles"
    state: absent
- name: Clone the dotfiles repo
  ansible.builtin.git:
    repo: "https://github.com/lkarasinski/dotfiles.git"
    dest: "/home/lkarasinski/dotfiles"
- name: Install stow
  pacman: name=stow
- name: Remove existing ~/.zshrc
  ansible.builtin.file: 
    path: "/home/lkarasinski/.zshrc"
    state: absent
- name: Run installation script
  shell: "chdir=/home/lkarasinski/dotfiles zsh ./install"
